routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // User Devices
    Route::delete('user-devices/destroy', 'UserDeviceController@massDestroy')->name('user-devices.massDestroy');
    Route::resource('user-devices', 'UserDeviceController');

    // Continents
    Route::delete('continents/destroy', 'ContinentController@massDestroy')->name('continents.massDestroy');
    Route::resource('continents', 'ContinentController');

    // Countries
    Route::delete('countries/destroy', 'CountryController@massDestroy')->name('countries.massDestroy');
    Route::resource('countries', 'CountryController');

    // Leagues
    Route::delete('leagues/destroy', 'LeagueController@massDestroy')->name('leagues.massDestroy');
    Route::post('leagues/media', 'LeagueController@storeMedia')->name('leagues.storeMedia');
    Route::post('leagues/ckmedia', 'LeagueController@storeCKEditorImages')->name('leagues.storeCKEditorImages');
    Route::resource('leagues', 'LeagueController');

    // Seasons
    Route::delete('seasons/destroy', 'SeasonController@massDestroy')->name('seasons.massDestroy');
    Route::resource('seasons', 'SeasonController');

    // Teams
    Route::delete('teams/destroy', 'TeamController@massDestroy')->name('teams.massDestroy');
    Route::resource('teams', 'TeamController');

    // Matches
    Route::delete('matches/destroy', 'MatchController@massDestroy')->name('matches.massDestroy');
    Route::resource('matches', 'MatchController');

    // Filters
    Route::delete('filters/destroy', 'FilterController@massDestroy')->name('filters.massDestroy');
    Route::post('filters/media', 'FilterController@storeMedia')->name('filters.storeMedia');
    Route::post('filters/ckmedia', 'FilterController@storeCKEditorImages')->name('filters.storeCKEditorImages');
    Route::resource('filters', 'FilterController');
});


\Illuminate\Support\Facades\Route::any('download', ['as' => 'download', 'uses' => 'Api\V1\Mobile\UsersController@download']);

app/League.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;

class League extends Model implements HasMedia
{
    use SoftDeletes, HasMediaTrait;

    public $table = 'leagues';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'sm',
        'name',
        'active',
        'is_cup',
        'name_en',
        'logo_path',
        'updated_at',
        'created_at',
        'deleted_at',
        'country_id',
        'predictions',
        'current_round',
        'current_stage',
        'live_standings',
        'current_season',
        'topscorer_cards',
        'topscorer_goals',
        'topscorer_assists',
    ];

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')->width(50)->height(50);
    }

    public function country()
    {
        return $this->belongsTo(Country::class, 'country_id');
    }
    public function news()
    {
        return $this->hasMany(News::class);
    }

    public function getLogoAttribute()
    {
        $file = $this->getMedia('logo')->last();

        if ($file) {
            $file->url = $file->getUrl();
        }

        return $file;
    }
    public function filters()
    {
      return $this->morphMany('App\Filter', 'imageable');
    }
}

app/Http/Controllers/Admin/LeagueController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Country;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroyLeagueRequest;
use App\Http\Requests\StoreLeagueRequest;
use App\Http\Requests\UpdateLeagueRequest;
use App\League;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class LeagueController extends Controller
{
    // use MediaUploadingTrait;

    public function index()
    {
        abort_if(Gate::denies('league_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $leagues = League::all();

        return view('admin.leagues.index', compact('leagues'));
    }

    public function create()
    {
        abort_if(Gate::denies('league_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $countries = Country::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.leagues.create', compact('countries'));
    }

    public function store(StoreLeagueRequest $request)
    {
        $league = League::create($request->all());

        if ($request->input('logo', false)) {
            $league->addMedia(storage_path('tmp/uploads/' . $request->input('logo')))->toMediaCollection('logo');
        }

        return redirect()->route('admin.leagues.index');
    }

    public function edit(League $league)
    {
        abort_if(Gate::denies('league_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $countries = Country::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $league->load('country');

        return view('admin.leagues.edit', compact('countries', 'league'));
    }

    public function update(UpdateLeagueRequest $request, League $league)
    {
        $league->update($request->all());

        if ($request->input('logo', false)) {
            if (!$league->logo || $request->input('logo') !== $league->logo->file_name) {
                $league->addMedia(storage_path('tmp/uploads/' . $request->input('logo')))->toMediaCollection('logo');
            }
        } elseif ($league->logo) {
            $league->logo->delete();
        }

        return redirect()->route('admin.leagues.index');
    }

    public function show(League $league)
    {
        abort_if(Gate::denies('league_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $league->load('country');

        return view('admin.leagues.show', compact('league'));
    }

    public function destroy(League $league)
    {
        abort_if(Gate::denies('league_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $league->delete();

        return back();
    }

    public function massDestroy(MassDestroyLeagueRequest $request)
    {
        League::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

app/Http/Controllers/Api/V1/Mobile/LeagueController.php
<?php

namespace App\Http\Controllers\Api\V1\Mobile;

use App\Http\Controllers\Controller;
use App\League;
use App\UserDevice;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Hash;
use function App\J_response;
use function App\send_email;
use function App\validate_Api_request;

class LeagueController extends Controller
{
    public function recordLeagues(){
         $client = new \GuzzleHttp\Client();
        $response = $client->request('GET', 'https://soccer.sportmonks.com/api/v2.0/leagues?api_token=6780XK6x95dDUxH71gYeQaAzfz0g34hr1S9mSh8H0CYRyhirxW8FNUiA3MwS&include=country');

        $leagues= json_decode($response->getBody(),true);
        
        foreach($leagues["data"] as $leag){
            $is_exist=League::where('id',$leag["id"])->first();
            if($is_exist){
                $league=$is_exist;
            }else{
                $league=new League;
                $league->id= $leag["id"];
            }
            $league->active=$leag["active"] ?1 :0;
            $league->name_en= $leag["name"];
            $league->logo_path= $leag["logo_path"];
            $league->is_cup= $leag["is_cup"];
            $league->current_season= $leag["current_season_id"];
            $league->current_round= $leag["current_round_id"];
            $league->current_stage= $leag["current_stage_id"];
            $league->live_standings= $leag["live_standings"]?1:0;
            $league->predictions= $leag["coverage"]["predictions"];
            $league->topscorer_assists= $leag["coverage"]["topscorer_assists"] ?1:0;
            $league->topscorer_cards= $leag["coverage"]["topscorer_cards"]?1:0;
            $league->topscorer_goals= $leag["coverage"]["topscorer_goals"]?1:0;
            $league->country_id= $leag["country"]["data"]["id"];
           $league->save();
        }
      
        return "database ready";
         


    }
    public function getLeagues(){
        return League::orderBy('id','desc')->paginate(20);
    }
   
}

resources/views/admin/leagues/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.league.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.leagues.store") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('sm') ? 'has-error' : '' }}">
                <label for="sm">{{ trans('cruds.league.fields.sm') }}</label>
                <input type="number" id="sm" name="sm" class="form-control" value="{{ old('sm', isset($league) ? $league->sm : '') }}" step="1">
                @if($errors->has('sm'))
                    <p class="help-block">
                        {{ $errors->first('sm') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.league.fields.sm_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('active') ? 'has-error' : '' }}">
                <label for="active">{{ trans('cruds.league.fields.active') }}</label>
                <input name="active" type="hidden" value="0">
                <input value="1" type="checkbox" id="active" name="active" {{ old('active', 0) == 1 ? 'checked' : '' }}>
                @if($errors->has('active'))
                    <p class="help-block">
                        {{ $errors->first('active') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.league.fields.active_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('country_id') ? 'has-error' : '' }}">
                <label for="country">{{ trans('cruds.league.fields.country') }}</label>
                <select name="country_id" id="country" class="form-control select2">
                    @foreach($countries as $id => $country)
                        <option value="{{ $id }}" {{ (isset($league) && $league->country ? $league->country->id : old('country_id')) == $id ? 'selected' : '' }}>{{ $country }}</option>
                    @endforeach
                </select>
                @if($errors->has('country_id'))
                    <p class="help-block">
                        {{ $errors->first('country_id') }}
                    </p>
                @endif
            </div>
            <div class="form-group {{ $errors->has('logo') ? 'has-error' : '' }}">
                <label for="logo">{{ trans('cruds.league.fields.logo') }}</label>
                <div class="needsclick dropzone" id="logo-dropzone">

                </div>
                @if($errors->has('logo'))
                    <p class="help-block">
                        {{ $errors->first('logo') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.league.fields.logo_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">{{ trans('cruds.league.fields.name') }}</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($league) ? $league->name : '') }}">
                @if($errors->has('name'))
                    <p class="help-block">
                        {{ $errors->first('name') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.league.fields.name_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('name_en') ? 'has-error' : '' }}">
                <label for="name_en">{{ trans('cruds.league.fields.name_en') }}</label>
                <input type="text" id="name_en" name="name_en" class="form-control" value="{{ old('name_en', isset($league) ? $league->name_en : '') }}">
                @if($errors->has('name_en'))
                    <p class="help-block">
                        {{ $errors->first('name_en') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.league.fields.name_en_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('is_cup') ? 'has-error' : '' }}">
                <label for="is_cup">{{ trans('cruds.league.fields.is_cup') }}</label>
                <input name="is_cup" type="hidden" value="0">
                <input value="1" type="checkbox" id="is_cup" name="is_cup" {{ old('is_cup', 0) == 1 ? 'checked' : '' }}>
                @if($errors->has('is_cup'))
                    <p class="help-block">
                        {{ $errors->first('is_cup') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.league.fields.is_cup_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('current_season') ? 'has-error' : '' }}">
                <label for="current_season">{{ trans('cruds.league.fields.current_season') }}</label>
                <input type="text" id="current_season" name="current_season" class="form-control" value="{{ old('current_season', isset($league) ? $league->current_season : '') }}">
                @if($errors->has('current_season'))
                    <p class="help-block">
                        {{ $errors->first('current_season') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.league.fields.current_season_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('current_round') ? 'has-error' : '' }}">
                <label for="current_round">{{ trans('cruds.league.fields.current_round') }}</label>
                <input type="text" id="current_round" name="current_round" class="form-control" value="{{ old('current_round', isset($league) ? $league->current_round : '') }}">
                @if($errors->has('current_round'))
                    <p class="help-block">
                        {{ $errors->first('current_round') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.league.fields.current_round_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('current_stage') ? 'has-error' : '' }}">
                <label for="current_stage">{{ trans('cruds.league.fields.current_stage') }}</label>
                <input type="text" id="current_stage" name="current_stage" class="form-control" value="{{ old('current_stage', isset($league) ? $league->current_stage : '') }}">
                @if($errors->has('current_stage'))
                    <p class="help-block">
                        {{ $errors->first('current_stage') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.league.fields.current_stage_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('live_standings') ? 'has-error' : '' }}">
                <label for="live_standings">{{ trans('cruds.league.fields.live_standings') }}</label>
                <input name="live_standings" type="hidden" value="0">
                <input value="1" type="checkbox" id="live_standings" name="live_standings" {{ old('live_standings', 0) == 1 ? 'checked' : '' }}>
                @if($errors->has('live_standings'))
                    <p class="help-block">
                        {{ $errors->first('live_standings') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.league.fields.live_standings_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('predictions') ? 'has-error' : '' }}">
                <label for="predictions">{{ trans('cruds.league.fields.predictions') }}</label>
                <input name="predictions" type="hidden" value="0">
                <input value="1" type="checkbox" id="predictions" name="predictions" {{ old('predictions', 0) == 1 ? 'checked' : '' }}>
                @if($errors->has('predictions'))
                    <p class="help-block">
                        {{ $errors->first('predictions') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.league.fields.predictions_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('topscorer_assists') ? 'has-error' : '' }}">
                <label for="topscorer_assists">{{ trans('cruds.league.fields.topscorer_assists') }}</label>
                <input name="topscorer_assists" type="hidden" value="0">
                <input value="1" type="checkbox" id="topscorer_assists" name="topscorer_assists" {{ old('topscorer_assists', 0) == 1 ? 'checked' : '' }}>
                @if($errors->has('topscorer_assists'))
                    <p class="help-block">
                        {{ $errors->first('topscorer_assists') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.league.fields.topscorer_assists_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('topscorer_cards') ? 'has-error' : '' }}">
                <label for="topscorer_cards">{{ trans('cruds.league.fields.topscorer_cards') }}</label>
                <input name="topscorer_cards" type="hidden" value="0">
                <input value="1" type="checkbox" id="topscorer_cards" name="topscorer_cards" {{ old('topscorer_cards', 0) == 1 ? 'checked' : '' }}>
                @if($errors->has('topscorer_cards'))
                    <p class="help-block">
                        {{ $errors->first('topscorer_cards') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.league.fields.topscorer_cards_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('topscorer_goals') ? 'has-error' : '' }}">
                <label for="topscorer_goals">{{ trans('cruds.league.fields.topscorer_goals') }}</label>
                <input name="topscorer_goals" type="hidden" value="0">
                <input value="1" type="checkbox" id="topscorer_goals" name="topscorer_goals" {{ old('topscorer_goals', 0) == 1 ? 'checked' : '' }}>
                @if($errors->has('topscorer_goals'))
                    <p class="help-block">
                        {{ $errors->first('topscorer_goals') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.league.fields.topscorer_goals_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>
@endsection

@section('scripts')
<script>
    Dropzone.options.logoDropzone = {
    url: '{{ route('admin.leagues.storeMedia') }}',
    maxFilesize: 2, // MB
    acceptedFiles: '.jpeg,.jpg,.png,.gif',
    maxFiles: 1,
    addRemoveLinks: true,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    params: {
      size: 2,
      width: 4096,
      height: 4096
    },
    success: function (file, response) {
      $('form').find('input[name="logo"]').remove()
      $('form').append('<input type="hidden" name="logo" value="' + response.name + '">')
    },
    removedfile: function (file) {
      file.previewElement.remove()
      $('form').find('input[name="logo"]').remove()
      this.options.maxFiles = this.options.maxFiles + 1
    },
    init: function () {
@if(isset($league) && $league->logo)
      var file = {!! json_encode($league->logo) !!}
          this.options.addedfile.call(this, file)
      this.options.thumbnail.call(this, file, file.url)
      file.previewElement.classList.add('dz-complete')
      $('form').append('<input type="hidden" name="logo" value="' + file.file_name + '">')
      this.options.maxFiles = this.options.maxFiles - 1
@endif
    },
    error: function (file, response) {
        if ($.type(response) === 'string') {
            var message = response //dropzone sends it's own error messages in string
        } else {
            var message = response.errors.file
        }
        file.previewElement.classList.add('dz-error')
        _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')
        _results = []
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            node = _ref[_i]
            _results.push(node.textContent = message)
        }

        return _results
    }
}
</script>
@stop

resources/views/admin/leagues/index.blade.php
@extends('layouts.admin')
@section('content')
@can('league_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.leagues.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.league.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.league.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.league.fields.sm') }}
                        </th>
                        <th>
                            {{ trans('cruds.league.fields.active') }}
                        </th>
                        <th>
                            {{ trans('cruds.league.fields.country') }}
                        </th>
                        <th>
                            {{ trans('cruds.league.fields.logo') }}
                        </th>
                        <th>
                            {{ trans('cruds.league.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.league.fields.name_en') }}
                        </th>
                        <th>
                            {{ trans('cruds.league.fields.is_cup') }}
                        </th>
                        <th>
                            {{ trans('cruds.league.fields.current_season') }}
                        </th>
                        <th>
                            {{ trans('cruds.league.fields.current_round') }}
                        </th>
                        <th>
                            {{ trans('cruds.league.fields.current_stage') }}
                        </th>
                        <th>
                            {{ trans('cruds.league.fields.live_standings') }}
                        </th>
                        <th>
                            {{ trans('cruds.league.fields.predictions') }}
                        </th>
                        <th>
                            {{ trans('cruds.league.fields.topscorer_assists') }}
                        </th>
                        <th>
                            {{ trans('cruds.league.fields.topscorer_cards') }}
                        </th>
                        <th>
                            {{ trans('cruds.league.fields.topscorer_goals') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($leagues as $key => $league)
                        <tr data-entry-id="{{ $league->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $league->sm ?? '' }}
                            </td>
                            <td>
                                {{ $league->active ? trans('global.yes') : trans('global.no') }}
                            </td>
                            <td>
                                {{ $league->country->name ?? '' }}
                            </td>
                            <td>
                                @if($league->logo)
                                    <a href="{{ $league->logo->getUrl() }}" target="_blank">
                                        <img src="{{ $league->logo->getUrl('thumb') }}" width="50px" height="50px">
                                    </a>
                                @endif
                            </td>
                            <td>
                                {{ $league->name ?? '' }}
                            </td>
                            <td>
                                {{ $league->name_en ?? '' }}
                            </td>
                            <td>
                                {{ $league->is_cup ? trans('global.yes') : trans('global.no') }}
                            </td>
                            <td>
                                {{ $league->current_season ?? '' }}
                            </td>
                            <td>
                                {{ $league->current_round ?? '' }}
                            </td>
                            <td>
                                {{ $league->current_stage ?? '' }}
                            </td>
                            <td>
                                {{ $league->live_standings ? trans('global.yes') : trans('global.no') }}
                            </td>
                            <td>
                                {{ $league->predictions ? trans('global.yes') : trans('global.no') }}
                            </td>
                            <td>
                                {{ $league->topscorer_assists ? trans('global.yes') : trans('global.no') }}
                            </td>
                            <td>
                                {{ $league->topscorer_cards ? trans('global.yes') : trans('global.no') }}
                            </td>
                            <td>
                                {{ $league->topscorer_goals ? trans('global.yes') : trans('global.no') }}
                            </td>
                            <td>
                                @can('league_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.leagues.show', $league->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan
                                @can('league_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.leagues.edit', $league->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan
                                @can('league_delete')
                                    <form action="{{ route('admin.leagues.destroy', $league->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.leagues.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
@can('league_delete')
  dtButtons.push(deleteButton)
@endcan

  $('.datatable:not(.ajaxTable)').DataTable({ buttons: dtButtons })
})

</script>
@endsection