routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // User Devices
    Route::delete('user-devices/destroy', 'UserDeviceController@massDestroy')->name('user-devices.massDestroy');
    Route::resource('user-devices', 'UserDeviceController');

    // Continents
    Route::delete('continents/destroy', 'ContinentController@massDestroy')->name('continents.massDestroy');
    Route::resource('continents', 'ContinentController');

    // Countries
    Route::delete('countries/destroy', 'CountryController@massDestroy')->name('countries.massDestroy');
    Route::resource('countries', 'CountryController');

    // Leagues
    Route::delete('leagues/destroy', 'LeagueController@massDestroy')->name('leagues.massDestroy');
    Route::post('leagues/media', 'LeagueController@storeMedia')->name('leagues.storeMedia');
    Route::post('leagues/ckmedia', 'LeagueController@storeCKEditorImages')->name('leagues.storeCKEditorImages');
    Route::resource('leagues', 'LeagueController');

    // Seasons
    Route::delete('seasons/destroy', 'SeasonController@massDestroy')->name('seasons.massDestroy');
    Route::resource('seasons', 'SeasonController');

    // Teams
    Route::delete('teams/destroy', 'TeamController@massDestroy')->name('teams.massDestroy');
    Route::resource('teams', 'TeamController');

    // Matches
    Route::delete('matches/destroy', 'MatchController@massDestroy')->name('matches.massDestroy');
    Route::resource('matches', 'MatchController');

    // Filters
    Route::delete('filters/destroy', 'FilterController@massDestroy')->name('filters.massDestroy');
    Route::post('filters/media', 'FilterController@storeMedia')->name('filters.storeMedia');
    Route::post('filters/ckmedia', 'FilterController@storeCKEditorImages')->name('filters.storeCKEditorImages');
    Route::resource('filters', 'FilterController');
});


\Illuminate\Support\Facades\Route::any('download', ['as' => 'download', 'uses' => 'Api\V1\Mobile\UsersController@download']);

app/UserDevice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class UserDevice extends Model
{
    use SoftDeletes;

    public $table = 'user_devices';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'token',
        'user_id',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Http/Controllers/Admin/UserDeviceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyUserDeviceRequest;
use App\Http\Requests\StoreUserDeviceRequest;
use App\Http\Requests\UpdateUserDeviceRequest;
use App\User;
use App\UserDevice;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class UserDeviceController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('user_device_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $userDevices = UserDevice::all();

        return view('admin.userDevices.index', compact('userDevices'));
    }

    public function create()
    {
        abort_if(Gate::denies('user_device_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $users = User::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.userDevices.create', compact('users'));
    }

    public function store(StoreUserDeviceRequest $request)
    {
        $userDevice = UserDevice::create($request->all());

        return redirect()->route('admin.user-devices.index');
    }

    public function edit(UserDevice $userDevice)
    {
        abort_if(Gate::denies('user_device_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $users = User::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $userDevice->load('user');

        return view('admin.userDevices.edit', compact('users', 'userDevice'));
    }

    public function update(UpdateUserDeviceRequest $request, UserDevice $userDevice)
    {
        $userDevice->update($request->all());

        return redirect()->route('admin.user-devices.index');
    }

    public function show(UserDevice $userDevice)
    {
        abort_if(Gate::denies('user_device_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $userDevice->load('user');

        return view('admin.userDevices.show', compact('userDevice'));
    }

    public function destroy(UserDevice $userDevice)
    {
        abort_if(Gate::denies('user_device_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $userDevice->delete();

        return back();
    }

    public function massDestroy(MassDestroyUserDeviceRequest $request)
    {
        UserDevice::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/userDevices/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.userDevice.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.user-devices.store") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('user_id') ? 'has-error' : '' }}">
                <label for="user">{{ trans('cruds.userDevice.fields.user') }}</label>
                <select name="user_id" id="user" class="form-control select2">
                    @foreach($users as $id => $user)
                        <option value="{{ $id }}" {{ (isset($userDevice) && $userDevice->user ? $userDevice->user->id : old('user_id')) == $id ? 'selected' : '' }}>{{ $user }}</option>
                    @endforeach
                </select>
                @if($errors->has('user_id'))
                    <p class="help-block">
                        {{ $errors->first('user_id') }}
                    </p>
                @endif
            </div>
            <div class="form-group {{ $errors->has('token') ? 'has-error' : '' }}">
                <label for="token">{{ trans('cruds.userDevice.fields.token') }}</label>
                <input type="text" id="token" name="token" class="form-control" value="{{ old('token', isset($userDevice) ? $userDevice->token : '') }}">
                @if($errors->has('token'))
                    <p class="help-block">
                        {{ $errors->first('token') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.userDevice.fields.token_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/userDevices/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.userDevice.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.user-devices.update", [$userDevice->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group {{ $errors->has('user_id') ? 'has-error' : '' }}">
                <label for="user">{{ trans('cruds.userDevice.fields.user') }}</label>
                <select name="user_id" id="user" class="form-control select2">
                    @foreach($users as $id => $user)
                        <option value="{{ $id }}" {{ (isset($userDevice) && $userDevice->user ? $userDevice->user->id : old('user_id')) == $id ? 'selected' : '' }}>{{ $user }}</option>
                    @endforeach
                </select>
                @if($errors->has('user_id'))
                    <p class="help-block">
                        {{ $errors->first('user_id') }}
                    </p>
                @endif
            </div>
            <div class="form-group {{ $errors->has('token') ? 'has-error' : '' }}">
                <label for="token">{{ trans('cruds.userDevice.fields.token') }}</label>
                <input type="text" id="token" name="token" class="form-control" value="{{ old('token', isset($userDevice) ? $userDevice->token : '') }}">
                @if($errors->has('token'))
                    <p class="help-block">
                        {{ $errors->first('token') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.userDevice.fields.token_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/userDevices/index.blade.php
@extends('layouts.admin')
@section('content')
@can('user_device_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.user-devices.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.userDevice.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.userDevice.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.userDevice.fields.user') }}
                        </th>
                        <th>
                            {{ trans('cruds.userDevice.fields.token') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($userDevices as $key => $userDevice)
                        <tr data-entry-id="{{ $userDevice->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $userDevice->user->name ?? '' }}
                            </td>
                            <td>
                                {{ $userDevice->token ?? '' }}
                            </td>
                            <td>
                                @can('user_device_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.user-devices.show', $userDevice->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan
                                @can('user_device_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.user-devices.edit', $userDevice->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan
                                @can('user_device_delete')
                                    <form action="{{ route('admin.user-devices.destroy', $userDevice->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.user-devices.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
@can('user_device_delete')
  dtButtons.push(deleteButton)
@endcan

  $('.datatable:not(.ajaxTable)').DataTable({ buttons: dtButtons })
})

</script>
@endsection

resources/views/admin/userDevices/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.userDevice.title') }}
    </div>

    <div class="card-body">
        <div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.userDevice.fields.user') }}
                        </th>
                        <td>
                            {{ $userDevice->user->name ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.userDevice.fields.token') }}
                        </th>
                        <td>
                            {{ $userDevice->token }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <a style="margin-top:20px;" class="btn btn-default" href="{{ url()->previous() }}">
                {{ trans('global.back_to_list') }}
            </a>
        </div>
    </div>
</div>
@endsection