routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // User Devices
    Route::delete('user-devices/destroy', 'UserDeviceController@massDestroy')->name('user-devices.massDestroy');
    Route::resource('user-devices', 'UserDeviceController');

    // Continents
    Route::delete('continents/destroy', 'ContinentController@massDestroy')->name('continents.massDestroy');
    Route::resource('continents', 'ContinentController');

    // Countries
    Route::delete('countries/destroy', 'CountryController@massDestroy')->name('countries.massDestroy');
    Route::resource('countries', 'CountryController');

    // Leagues
    Route::delete('leagues/destroy', 'LeagueController@massDestroy')->name('leagues.massDestroy');
    Route::post('leagues/media', 'LeagueController@storeMedia')->name('leagues.storeMedia');
    Route::post('leagues/ckmedia', 'LeagueController@storeCKEditorImages')->name('leagues.storeCKEditorImages');
    Route::resource('leagues', 'LeagueController');

    // Seasons
    Route::delete('seasons/destroy', 'SeasonController@massDestroy')->name('seasons.massDestroy');
    Route::resource('seasons', 'SeasonController');

    // Teams
    Route::delete('teams/destroy', 'TeamController@massDestroy')->name('teams.massDestroy');
    Route::resource('teams', 'TeamController');

    // Matches
    Route::delete('matches/destroy', 'MatchController@massDestroy')->name('matches.massDestroy');
    Route::resource('matches', 'MatchController');

    // Filters
    Route::delete('filters/destroy', 'FilterController@massDestroy')->name('filters.massDestroy');
    Route::post('filters/media', 'FilterController@storeMedia')->name('filters.storeMedia');
    Route::post('filters/ckmedia', 'FilterController@storeCKEditorImages')->name('filters.storeCKEditorImages');
    Route::resource('filters', 'FilterController');
});


\Illuminate\Support\Facades\Route::any('download', ['as' => 'download', 'uses' => 'Api\V1\Mobile\UsersController@download']);

app/Continent.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Continent extends Model
{
    use SoftDeletes;

    public $table = 'continents';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'sm',
        'name',
        'created_at',
        'updated_at',
        'deleted_at',
    ];
}

app/Http/Controllers/Admin/ContinentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Continent;
use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyContinentRequest;
use App\Http\Requests\StoreContinentRequest;
use App\Http\Requests\UpdateContinentRequest;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class ContinentController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('continent_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $continents = Continent::all();

        return view('admin.continents.index', compact('continents'));
    }

    public function create()
    {
        abort_if(Gate::denies('continent_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.continents.create');
    }

    public function store(StoreContinentRequest $request)
    {
        $continent = Continent::create($request->all());

        return redirect()->route('admin.continents.index');
    }

    public function edit(Continent $continent)
    {
        abort_if(Gate::denies('continent_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.continents.edit', compact('continent'));
    }

    public function update(UpdateContinentRequest $request, Continent $continent)
    {
        $continent->update($request->all());

        return redirect()->route('admin.continents.index');
    }

    public function show(Continent $continent)
    {
        abort_if(Gate::denies('continent_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.continents.show', compact('continent'));
    }

    public function destroy(Continent $continent)
    {
        abort_if(Gate::denies('continent_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $continent->delete();

        return back();
    }

    public function massDestroy(MassDestroyContinentRequest $request)
    {
        Continent::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

app/Http/Controllers/Api/V1/Mobile/ContinentController.php
<?php

namespace App\Http\Controllers\Api\V1\Mobile;

use App\Http\Controllers\Controller;
use App\Continent;
use App\UserDevice;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Hash;
use function App\J_response;
use function App\send_email;
use function App\validate_Api_request;

class ContinentController extends Controller
{
    public function getAllContinents(){
        $client = new \GuzzleHttp\Client();
        $response = $client->request('GET', 'https://soccer.sportmonks.com/api/v2.0/continents?api_token=6780XK6x95dDUxH71gYeQaAzfz0g34hr1S9mSh8H0CYRyhirxW8FNUiA3MwS');
        $Continents= json_decode($response->getBody(),true);
        foreach($Continents["data"] as $Continent){
             $contin=new Continent;
             $contin->id=$Continent["id"];
             $contin->name=$Continent["name"];
             $contin->save();
        }
        return true;
    }
   
}

resources/views/admin/continents/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.continent.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.continents.store") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('sm') ? 'has-error' : '' }}">
                <label for="sm">{{ trans('cruds.continent.fields.sm') }}</label>
                <input type="number" id="sm" name="sm" class="form-control" value="{{ old('sm', isset($continent) ? $continent->sm : '') }}" step="1">
                @if($errors->has('sm'))
                    <p class="help-block">
                        {{ $errors->first('sm') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.continent.fields.sm_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">{{ trans('cruds.continent.fields.name') }}</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($continent) ? $continent->name : '') }}">
                @if($errors->has('name'))
                    <p class="help-block">
                        {{ $errors->first('name') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.continent.fields.name_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/continents/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.continent.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.continents.update", [$continent->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group {{ $errors->has('sm') ? 'has-error' : '' }}">
                <label for="sm">{{ trans('cruds.continent.fields.sm') }}</label>
                <input type="number" id="sm" name="sm" class="form-control" value="{{ old('sm', isset($continent) ? $continent->sm : '') }}" step="1">
                @if($errors->has('sm'))
                    <p class="help-block">
                        {{ $errors->first('sm') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.continent.fields.sm_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">{{ trans('cruds.continent.fields.name') }}</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($continent) ? $continent->name : '') }}">
                @if($errors->has('name'))
                    <p class="help-block">
                        {{ $errors->first('name') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.continent.fields.name_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/continents/index.blade.php
@extends('layouts.admin')
@section('content')
@can('continent_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.continents.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.continent.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.continent.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.continent.fields.sm') }}
                        </th>
                        <th>
                            {{ trans('cruds.continent.fields.name') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($continents as $key => $continent)
                        <tr data-entry-id="{{ $continent->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $continent->sm ?? '' }}
                            </td>
                            <td>
                                {{ $continent->name ?? '' }}
                            </td>
                            <td>
                                @can('continent_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.continents.show', $continent->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan
                                @can('continent_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.continents.edit', $continent->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan
                                @can('continent_delete')
                                    <form action="{{ route('admin.continents.destroy', $continent->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.continents.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
@can('continent_delete')
  dtButtons.push(deleteButton)
@endcan

  $('.datatable:not(.ajaxTable)').DataTable({ buttons: dtButtons })
})

</script>
@endsection

resources/views/admin/continents/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.continent.title') }}
    </div>

    <div class="card-body">
        <div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.continent.fields.sm') }}
                        </th>
                        <td>
                            {{ $continent->sm }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.continent.fields.name') }}
                        </th>
                        <td>
                            {{ $continent->name }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <a style="margin-top:20px;" class="btn btn-default" href="{{ url()->previous() }}">
                {{ trans('global.back_to_list') }}
            </a>
        </div>
    </div>
</div>
@endsection