routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // User Devices
    Route::delete('user-devices/destroy', 'UserDeviceController@massDestroy')->name('user-devices.massDestroy');
    Route::resource('user-devices', 'UserDeviceController');

    // Continents
    Route::delete('continents/destroy', 'ContinentController@massDestroy')->name('continents.massDestroy');
    Route::resource('continents', 'ContinentController');

    // Countries
    Route::delete('countries/destroy', 'CountryController@massDestroy')->name('countries.massDestroy');
    Route::resource('countries', 'CountryController');

    // Leagues
    Route::delete('leagues/destroy', 'LeagueController@massDestroy')->name('leagues.massDestroy');
    Route::post('leagues/media', 'LeagueController@storeMedia')->name('leagues.storeMedia');
    Route::post('leagues/ckmedia', 'LeagueController@storeCKEditorImages')->name('leagues.storeCKEditorImages');
    Route::resource('leagues', 'LeagueController');

    // Seasons
    Route::delete('seasons/destroy', 'SeasonController@massDestroy')->name('seasons.massDestroy');
    Route::resource('seasons', 'SeasonController');

    // Teams
    Route::delete('teams/destroy', 'TeamController@massDestroy')->name('teams.massDestroy');
    Route::resource('teams', 'TeamController');

    // Matches
    Route::delete('matches/destroy', 'MatchController@massDestroy')->name('matches.massDestroy');
    Route::resource('matches', 'MatchController');

    // Filters
    Route::delete('filters/destroy', 'FilterController@massDestroy')->name('filters.massDestroy');
    Route::post('filters/media', 'FilterController@storeMedia')->name('filters.storeMedia');
    Route::post('filters/ckmedia', 'FilterController@storeCKEditorImages')->name('filters.storeCKEditorImages');
    Route::resource('filters', 'FilterController');
});


\Illuminate\Support\Facades\Route::any('download', ['as' => 'download', 'uses' => 'Api\V1\Mobile\UsersController@download']);

app/Filter.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;

class Filter extends Model implements HasMedia
{
    use HasMediaTrait;

    public $table = 'filters';

    protected $appends = [
        'image',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
       
    ];

    protected $fillable = [
        'url',
        'imageable_id',
        'created_at',
        'updated_at',
       'imageable_type',
    ];

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')->width(50)->height(50);
    }

    public function getImageAttribute()
    {
        $file = $this->getMedia('image')->last();

        if ($file) {
            $file->url       = $file->getUrl();
            $file->thumbnail = $file->getUrl('thumb');
        }

        return $file;
    }
    
    public function imageable()
    {
        return $this->morphTo();
    }
}

app/Http/Controllers/Admin/FilterController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Filter;
use App\League;
use App\Team;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroyFilterRequest;
use App\Http\Requests\StoreFilterRequest;
use App\Http\Requests\UpdateFilterRequest;
use Gate;
use Image;
use Exception;
use Illuminate\Http\Request;
use Spatie\MediaLibrary\Models\Media;
use Symfony\Component\HttpFoundation\Response;

class FilterController extends Controller
{
    // use MediaUploadingTrait;

    public function index()
    {
        abort_if(Gate::denies('filter_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $filters = Filter::all();

        return view('admin.filters.index', compact('filters'));
    }

    public function create()
    {
        abort_if(Gate::denies('filter_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $leagues = League::all()->pluck('name_en', 'id')->prepend(trans('global.pleaseSelect'), '');
        $teams = Team::all()->pluck('name_en', 'id')->prepend(trans('global.pleaseSelect'), '');
        return view('admin.filters.create', compact('leagues','teams'));
    }

    public function store(StoreFilterRequest $request)
    {
        $type=$request->imageable_type =='App\Team'?'team':'league';
        $filter=new Filter;
        $filter->imageable_type=$request->imageable_type;
        $filter->imageable_id=$request->imageable_id;
        $img=$request->image;
        if($img){
            $dest=public_path().'/uploads/filters';
            if(!file_exists($dest)){
                mkdir($dest, 0777, true);
            }
            $filename = $type."-" .$request->imageable_id . "-" . time()  . '.' . $img->getClientOriginalExtension();
            try{
               
               Image::make($img)->save($dest.'/'.$filename);
            }catch(Exception $e){
                return $e->getMessage(); 
               
            }
            $filter->url= $filename; 
            
        }
        $filter->save();

        // $filter = Filter::create($request->all());

        // if ($request->input('image', false)) {
        //     $filter->addMedia(storage_path('tmp/uploads/' . $request->input('image')))->toMediaCollection('image');
        // }

        // if ($media = $request->input('ck-media', false)) {
        //     Media::whereIn('id', $media)->update(['model_id' => $filter->id]);
        // }

        return redirect()->route('admin.filters.index');
    }

    public function edit(Filter $filter)
    {
        abort_if(Gate::denies('filter_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.filters.edit', compact('filter'));
    }

    public function update(UpdateFilterRequest $request, Filter $filter)
    {
        $filter->update($request->all());

        if ($request->input('image', false)) {
            if (!$filter->image || $request->input('image') !== $filter->image->file_name) {
                $filter->addMedia(storage_path('tmp/uploads/' . $request->input('image')))->toMediaCollection('image');
            }
        } elseif ($filter->image) {
            $filter->image->delete();
        }

        return redirect()->route('admin.filters.index');
    }

    public function show(Filter $filter)
    {
        abort_if(Gate::denies('filter_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.filters.show', compact('filter'));
    }

    public function destroy(Filter $filter)
    {
        abort_if(Gate::denies('filter_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $filter->delete();

        return back();
    }

    public function massDestroy(MassDestroyFilterRequest $request)
    {
        Filter::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }

    public function storeCKEditorImages(Request $request)
    {
        abort_if(Gate::denies('filter_create') && Gate::denies('filter_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $model         = new Filter();
        $model->id     = $request->input('crud_id', 0);
        $model->exists = true;
        $media         = $model->addMediaFromRequest('upload')->toMediaCollection('ck-media', 'public');

        return response()->json(['id' => $media->id, 'url' => $media->getUrl()], Response::HTTP_CREATED);
    }
}

app/Http/Controllers/Api/V1/Mobile/FilterController.php
<?php

namespace App\Http\Controllers\Api\V1\Mobile;

use App\Http\Controllers\Controller;
use App\Filter;
use App\Team;
use App\League;
use App\Match;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use function App\J_response;
use function App\validate_Api_request;
use App\Http\Resources\FilterTeamResource;
use App\Http\Resources\FilterResource;
use App\Http\Resources\FilterLeagueResource;

class FilterController extends Controller
{
    public function getFilters(Request $request){
        $input = $request->input();
        $validator = validate_Api_request($input, [
            'filterable_type' => 'in:team,league',
            'name'=>'string|max:60',
        ]);
        if ($validator['status'] != 200) {
            return $validator;
        }
        $filterable_type=$request->filterable_type;
        $name=$request->name;
        $teams=Team::has('filters')->get();
        $leagues=League::has('filters')->get();
        if($filterable_type){
            if($filterable_type=='team'){
                $leagues=collect([]);
            }else{
                $teams=collect([]);
            }
        }
        if($name){
            $teams=Team::has('filters')->where('name_en','like',"%{$name}%")->orWhere('name','like',"%{$name}%")->get();
            $leagues=League::has('filters')->where('name_en','like',"%{$name}%")->orWhere('name','like',"%{$name}%")->get();
        }
        $leagueFilters=(array) FilterLeagueResource::collection($leagues);
        $teamFilters=(array) FilterTeamResource::collection($teams);
        $data=[];
         foreach($teamFilters['collection'] as $filter){
             array_push($data,$filter);
         }
         foreach($leagueFilters['collection'] as $filter){
             array_push($data,$filter);
         }
        return J_response(\Illuminate\Http\Response::HTTP_OK, 'Filters Retrieved ', collect($data));
   }

   public function getMatchFilters(Request $request){
    $input = $request->input();
    $validator = validate_Api_request($input, [
        'match_id'=>'required|exists:matches,id'
    ]);
    if ($validator['status'] != 200) {
        return $validator;
    }
    $match=Match::find($request->match_id);
    if($match){
        $request->merge(['localId'=>$match->local_team->id]);
        
      $data= [
            $match->local_team?new FilterTeamResource($match->local_team):'',
            $match->visitor_team?new FilterTeamResource($match->visitor_team):'',
            $match->league?new FilterLeagueResource($match->league):'',
        ];
        return J_response(\Illuminate\Http\Response::HTTP_OK, 'Filters Retrieved ', collect($data));

    }
         
   }


}

resources/views/filters/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.filter.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.filters.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="imageable">{{ trans('cruds.filter.fields.imageable') }}</label>
                <input class="form-control {{ $errors->has('imageable') ? 'is-invalid' : '' }}" type="number" name="imageable" id="imageable" value="{{ old('imageable') }}" step="1" required>
                @if($errors->has(''))
                    <span class="text-danger">{{ $errors->first('') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.filter.fields.imageable_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="imageable_type">{{ trans('cruds.filter.fields.imageable_type') }}</label>
                <input class="form-control {{ $errors->has('imageable_type') ? 'is-invalid' : '' }}" type="text" name="imageable_type" id="imageable_type" value="{{ old('imageable_type', '') }}" required>
                @if($errors->has(''))
                    <span class="text-danger">{{ $errors->first('') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.filter.fields.imageable_type_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="image">{{ trans('cruds.filter.fields.image') }}</label>
                <div class="needsclick dropzone {{ $errors->has('image') ? 'is-invalid' : '' }}" id="image-dropzone">
                </div>
                @if($errors->has(''))
                    <span class="text-danger">{{ $errors->first('') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.filter.fields.image_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    Dropzone.options.imageDropzone = {
    url: '{{ route('admin.filters.storeMedia') }}',
    maxFilesize: 2, // MB
    acceptedFiles: '.jpeg,.jpg,.png,.gif',
    maxFiles: 1,
    addRemoveLinks: true,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    params: {
      size: 2,
      width: 4096,
      height: 4096
    },
    success: function (file, response) {
      $('form').find('input[name="image"]').remove()
      $('form').append('<input type="hidden" name="image" value="' + response.name + '">')
    },
    removedfile: function (file) {
      file.previewElement.remove()
      if (file.status !== 'error') {
        $('form').find('input[name="image"]').remove()
        this.options.maxFiles = this.options.maxFiles + 1
      }
    },
    init: function () {
@if(isset($filter) && $filter->image)
      var file = {!! json_encode($filter->image) !!}
          this.options.addedfile.call(this, file)
      this.options.thumbnail.call(this, file, '{{ $filter->image->getUrl('thumb') }}')
      file.previewElement.classList.add('dz-complete')
      $('form').append('<input type="hidden" name="image" value="' + file.file_name + '">')
      this.options.maxFiles = this.options.maxFiles - 1
@endif
    },
    error: function (file, response) {
        if ($.type(response) === 'string') {
            var message = response //dropzone sends it's own error messages in string
        } else {
            var message = response.errors.file
        }
        file.previewElement.classList.add('dz-error')
        _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')
        _results = []
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            node = _ref[_i]
            _results.push(node.textContent = message)
        }

        return _results
    }
}
</script>
@endsection

resources/views/filters/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.filter.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.filters.update", [$filter->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="imageable">{{ trans('cruds.filter.fields.imageable') }}</label>
                <input class="form-control {{ $errors->has('imageable') ? 'is-invalid' : '' }}" type="number" name="imageable" id="imageable" value="{{ old('imageable', $filter->imageable) }}" step="1" required>
                @if($errors->has(''))
                    <span class="text-danger">{{ $errors->first('') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.filter.fields.imageable_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="imageable_type">{{ trans('cruds.filter.fields.imageable_type') }}</label>
                <input class="form-control {{ $errors->has('imageable_type') ? 'is-invalid' : '' }}" type="text" name="imageable_type" id="imageable_type" value="{{ old('imageable_type', $filter->imageable_type) }}" required>
                @if($errors->has(''))
                    <span class="text-danger">{{ $errors->first('') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.filter.fields.imageable_type_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="image">{{ trans('cruds.filter.fields.image') }}</label>
                <div class="needsclick dropzone {{ $errors->has('image') ? 'is-invalid' : '' }}" id="image-dropzone">
                </div>
                @if($errors->has(''))
                    <span class="text-danger">{{ $errors->first('') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.filter.fields.image_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    Dropzone.options.imageDropzone = {
    url: '{{ route('admin.filters.storeMedia') }}',
    maxFilesize: 2, // MB
    acceptedFiles: '.jpeg,.jpg,.png,.gif',
    maxFiles: 1,
    addRemoveLinks: true,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    params: {
      size: 2,
      width: 4096,
      height: 4096
    },
    success: function (file, response) {
      $('form').find('input[name="image"]').remove()
      $('form').append('<input type="hidden" name="image" value="' + response.name + '">')
    },
    removedfile: function (file) {
      file.previewElement.remove()
      if (file.status !== 'error') {
        $('form').find('input[name="image"]').remove()
        this.options.maxFiles = this.options.maxFiles + 1
      }
    },
    init: function () {
@if(isset($filter) && $filter->image)
      var file = {!! json_encode($filter->image) !!}
          this.options.addedfile.call(this, file)
      this.options.thumbnail.call(this, file, '{{ $filter->image->getUrl('thumb') }}')
      file.previewElement.classList.add('dz-complete')
      $('form').append('<input type="hidden" name="image" value="' + file.file_name + '">')
      this.options.maxFiles = this.options.maxFiles - 1
@endif
    },
    error: function (file, response) {
        if ($.type(response) === 'string') {
            var message = response //dropzone sends it's own error messages in string
        } else {
            var message = response.errors.file
        }
        file.previewElement.classList.add('dz-error')
        _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')
        _results = []
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            node = _ref[_i]
            _results.push(node.textContent = message)
        }

        return _results
    }
}
</script>
@endsection

resources/views/filters/index.blade.php
@extends('layouts.admin')
@section('content')
@can('filter_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.filters.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.filter.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.filter.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Filter">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.filter.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.filter.fields.imageable') }}
                        </th>
                        <th>
                            {{ trans('cruds.filter.fields.imageable_type') }}
                        </th>
                        <th>
                            {{ trans('cruds.filter.fields.image') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($filters as $key => $filter)
                        <tr data-entry-id="{{ $filter->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $filter->id ?? '' }}
                            </td>
                            <td>
                                {{ $filter->imageable ?? '' }}
                            </td>
                            <td>
                                {{ $filter->imageable_type ?? '' }}
                            </td>
                            <td>
                                @if($filter->image)
                                    <a href="{{ $filter->image->getUrl() }}" target="_blank">
                                        <img src="{{ $filter->image->getUrl('thumb') }}" width="50px" height="50px">
                                    </a>
                                @endif
                            </td>
                            <td>
                                @can('filter_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.filters.show', $filter->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('filter_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.filters.edit', $filter->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('filter_delete')
                                    <form action="{{ route('admin.filters.destroy', $filter->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('filter_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.filters.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Filter:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

resources/views/filters/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.filter.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.filters.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.filter.fields.id') }}
                        </th>
                        <td>
                            {{ $filter->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.filter.fields.imageable') }}
                        </th>
                        <td>
                            {{ $filter->imageable }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.filter.fields.imageable_type') }}
                        </th>
                        <td>
                            {{ $filter->imageable_type }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.filter.fields.image') }}
                        </th>
                        <td>
                            @if($filter->image)
                                <a href="{{ $filter->image->getUrl() }}" target="_blank">
                                    <img src="{{ $filter->image->getUrl('thumb') }}" width="50px" height="50px">
                                </a>
                            @endif
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.filters.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection